"""Render docs/m0.md from data/results. Prose is here; every number is read from the results."""
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "data" / "results"
s = json.loads((R / "summary.json").read_text())
df = pd.read_csv(R / "event_table.csv")
u = df[df.usable]
snap = pd.read_csv(R / "spread_snapshot.csv")

def f(x, n=2): return "n/a" if x is None else f"{x:.{n}f}"
def sl(d): return f"**{f(d['pdr'])} ± {f(d['se'])}**"
def row(k, key):
    r = s[key]["rungs"][k]; return f"| {k} | {r['n']} | {f(r['mean'])} | {f(r['median'])} | {sl(r['slope'])} |"
def block(key, title):
    lit = s[key]["rtoken_literature_convention"]; un = s[key]["underlying"]; rb = s[key]["robustness_2000"]; d3 = rb["drop_top3_yield"]
    return f"""**{title}** — n = {s[key]['n_after_floor']}

| Measurement | n | mean of ratios | median of ratios | slope PDR ± s.e. |
|---|---|---|---|---|
{chr(10).join(row(k, key) for k in ['overnight_2000','premarket_0400','open_0930','open_1000','close_1600'])}
| rToken, close(D−1 16:00 ET) → open(D 09:30 ET) | {lit['n']} | {f(lit['mean'])} | {f(lit['median'])} | {sl(lit['slope'])} |
| Underlying, close(D−1) → open(D), daily bars | {un['n']} | {f(un['mean'])} | {f(un['median'])} | {sl(un['slope'])} |

20:00 ET rung, robustness: leave-one-out range [{f(rb['loo_min'])}, {f(rb['loo_max'])}]; without the three highest-yield events ({', '.join(rb['top3_symbols'])}) the slope is {f(d3['pdr'])} ± {f(d3['se'])} (n = {d3['n']}); ratio of sums Σ(P_pre − P_post)/Σ D = {f(rb['ratio_of_sums'])}.
"""

c = s["clean_2000_floor_0.2"]; cr = c["rungs"]["overnight_2000"]["slope"]; c3 = c["robustness_2000"]["drop_top3_yield"]
a = s["floor_None"]; ar = a["rungs"]["overnight_2000"]["slope"]; a3 = a["robustness_2000"]["drop_top3_yield"]
excl = "\n".join(f"| {e['event_id']} | {e['reason']} |" for e in a["exclusions"])
mism = df[df.div_check.str.startswith("AMOUNT")]
mism_rows = "\n".join(f"| {r.event_id} | {r.gross} | {r.div_check.replace('AMOUNT MISMATCH: ', '')} |" for r in mism.itertuples())
agree = int(df.div_check.str.startswith("Yahoo agrees").sum())
hi = u[u.yield_pct >= 0.5].sort_values("yield_pct", ascending=False)
hi_rows = "\n".join(f"| {r.event_id} | {r.yield_pct:.2f} | {int(r.gap_min)} | {'yes' if r.monday else ''} | {r.pdr_overnight_2000:.2f} | {r.pdr_literature:.2f} | {r.u_pdr:.2f} |" for r in hi.itertuples())
n_mon = int(u.monday.sum()); n_gap = int((u.gap_min <= 5).sum()); n_clean = int(((u.gap_min <= 5) & (~u.monday.astype(bool))).sum())
empty = int(snap.spread_bp.isna().sum())

doc = f"""# M0 — The event study

Rendered by `python scripts/render_m0.py` from `data/results/`, which `python -m exnight.calendar && python -m exnight.eventstudy && python -m exnight.analysis` regenerate from the saved sources and raw candles. `tests/test_m0_figures.py` asserts the figures quoted here against the results.

Labels: **DOCUMENTED** (first-party Bitget page, saved and checksummed), **OBSERVED** (we ran it, date given), **ASSUMED** (unverified). The verification trail is `docs/verification.md`.

## 1. Question

When a US share goes ex-dividend its price drops by a fraction of the dividend — about 0.77 in the classic US studies. Bitget rTokens are 1:1-backed tokens of those shares trading in USDT on a 24/5 venue, with the dividend paid separately in USDT net of 30% withholding (clean-price model, DOCUMENTED). Nobody had measured how *that* market prices the ex-date.

H₀: the rToken's price-drop ratio (PDR) equals the underlying's.

## 2. Sample — the denominator

- **Source:** Bitget support notice 12560603890079, "Dividend Distribution Completed for 63 Stocks", 2026-07-24 (DOCUMENTED). Ticker, ex-date, payment date and dividend per share for **63 distributions on 59 rTokens**, ex-dates 2026-06-11 → 2026-07-21; 30% withholding stated in the same notice.
- **63 events in the ledger**, regenerated byte-for-byte by `python -m exnight.calendar`.
- **{a['events_usable']} usable.** Exclusions:

| Event | Reason |
|---|---|
{excl}

  All three were re-listed after their ex-dates (`launchTime` moved to 2026-07-15 / 2026-09-03; rSOXS's is the day of its 1:10 reverse split). Intraday history before a re-listing does not exist.

- **Amount cross-check** against Yahoo Finance dividend events (third-party): {agree} of 63 agree to three decimals. The rest:

| Event | Bitget | Third-party |
|---|---|---|
{mism_rows}

  rSOXS is the 1:10 reverse split (Yahoo's figure is split-adjusted). rTSM, rBABA and rMDT are foreign issuers/ADRs; Bitget's lower figure is plausibly after foreign withholding, before the 30% US withholding. Bitget's figure is used because it is what holders were paid on; the discrepancy stays on the event.
- **Price data:** Bitget UTA v3 1-minute candles. OBSERVED: split back-adjusted; bars before `launchTime` are a backfilled reference series and are dropped; **candle volume tracks the US consolidated tape, not rToken fills**, so nothing here infers liquidity from volume. Underlying: Yahoo daily bars, used only for the underlying.

## 3. Measurement

rTokens trade continuously through the US overnight, so there is no single open. The engine takes one pre-event price and a ladder of post-event prices.

- **P_pre:** last 1-minute close strictly before **20:00 ET on the last NYSE trading day before the ex-date** (weekends and NYSE holidays skipped; Bitget printed bars on both in-sample holidays, so the calendar is applied explicitly). 20:00 ET is the US after-hours close — the last moment the token is unambiguously cum-dividend — and, in summer, 00:00 UTC, the time at which Bitget settles dividends on its stock perps (DOCUMENTED, article 12560603895292; whether the rToken adjustment is keyed to 20:00 ET or to 00:00 UTC cannot be told apart in a summer-only sample).
- **P_post:** first 1-minute close at or after each of 20:00 ET (D−1), 04:00, 09:30, 10:00 and 16:00 ET on D. **PDR = (P_pre − P_post) / gross dividend.**
- The 20:00 rung is only a measurement of the adjustment itself when the pre and post bars are adjacent. The gap is recorded per event: {n_gap} of {a['events_usable']} events have pre→post ≤ 5 minutes; {n_mon} events are Monday-type (ex-date after a weekend or holiday), where that rung spans the whole weekend. The **clean subset** is gap ≤ 5 min and not Monday-type: n = {n_clean}.
- **Literature convention** for the like-for-like comparison: rToken close before 16:00 ET D−1 → first bar at/after 09:30 ET D; underlying close(D−1) → open(D).
- **Estimator.** A ratio's noise scales with 1/yield: MU pays $0.15 on a ~$1,000 token (0.015%), so one ordinary minute becomes a PDR of ±200. The headline is therefore the cross-sectional regression of ex-day return on dividend yield, `r = a − PDR·(D/P) + e`, whose slope is the PDR. Because a slope can be carried by a few high-yield points, every table reports the leave-one-out range, the slope without the three highest-yield events, and the ratio of sums. Means and medians of the raw ratios are shown beside it.

## 4. Results

{block('clean_2000_floor_0.2', 'Clean subset, yield ≥ 0.2%')}
{block('clean_2000', 'Clean subset, all yields')}
{block('floor_None', 'All usable events')}
{block('floor_0.5', 'Yield ≥ 0.5%')}

### 4.1 Event by event, yield ≥ 0.5%

| Event | Yield % | pre→post gap (min) | Monday-type | PDR at 20:00 ET | PDR close→open | Underlying PDR |
|---|---|---|---|---|---|---|
{hi_rows}

## 5. What the sample supports

**A discrete adjustment at the after-hours close, of roughly the gross dividend, is visible in the liquid higher-yield ETFs.** rBITI 29.16 → 27.73 on a $1.45 dividend (0.99), rSQQQ 0.81, rSCHD 0.79, rSPXU 1.07, rPSQ 0.70, rPM 1.03, rDIS 0.91 — each in the first bar after 20:00 ET. On the clean weekday subset the pooled slope is {f(cr['pdr'])} ± {f(cr['se'])} (n = {cr['n']}), with a leave-one-out range of [{f(c['robustness_2000']['loo_min'])}, {f(c['robustness_2000']['loo_max'])}].

**That precision comes from three leveraged ETFs.** Without rSPXU, rSQQQ and rBITI the clean-subset slope is {f(c3['pdr'])} ± {f(c3['se'])}; on all events, without rHIMX, rOPRA and rBITI it is {f(a3['pdr'])} ± {f(a3['se'])}. The ratio-of-sums estimator gives {f(c['robustness_2000']['ratio_of_sums'])} on the clean subset and {f(a['robustness_2000']['ratio_of_sums'])} on all events. **Once the three most informative events are removed the sample cannot distinguish 0.70 from 1.00.**

**Monday-type ex-dates are not adjusted at Friday 20:00 ET.** rKO and rMO show exactly 0.00 at that rung and the drop appears by Monday pre-market. With {n_mon} such events and no weekend bars for most of them, the timing cannot be located more precisely.

**On the literature's own convention the rToken and the underlying are indistinguishable.** Close-to-open, all events: rToken {sl(a['rtoken_literature_convention']['slope'])} vs underlying {sl(a['underlying']['slope'])}. Both are consistent with the classic ~0.77 and with each other. **H₀ is not rejected.** Overnight variance is far larger than the dividend for almost every event; separating a 0.1 difference in PDR at that horizon would need several hundred events.

**Liquidity.** No historical order book exists. A live snapshot at 2026-09-16 11:25 UTC (07:25 ET) found **{empty} of {len(snap)} sample books empty**; the {len(snap) - empty} quoted showed median spread {snap.spread_bp.median():.0f} bp and top-of-book depth of ${snap.dropna(subset=['spread_bp'])[['top_ask_usdt','top_bid_usdt']].min(axis=1).min():,.0f}–${snap.dropna(subset=['spread_bp'])[['top_ask_usdt','top_bid_usdt']].max(axis=1).max():,.0f}. One snapshot at one hour, labelled OBSERVED-NOW. The sample was taken in pre-market, so it does not answer regular-session StockRoute depth and cannot support a general liquidity conclusion.

## 6. Regime verdict (spec §0.6)

The point estimate at the moment of adjustment is ≈1.0, above the 0.70 that holders net — the **EXIT** regime: sell before 20:00 ET on D−1, re-enter after. But the evidence that the PDR exceeds 0.70 rests on three events, and every other estimator or subset is consistent with 0.70. **The verdict is "EXIT indicated, not established."** The strategy engine must carry the PDR as a distribution, not a number; net of two fees, a crossed spread and books that are often empty, the minimum-edge threshold will return HOLD for most events. That is decided by these figures, not in advance.

## 7. Not established here

- **Eligibility.** Bitget's snapshot time is unpublished ("at the time of the snapshot"); `eligibility_verified` is false on every event and BUY signals are suppressed. EXIT does not depend on eligibility, which is why it can be evaluated.
- **Confounders.** No event is yet screened for contemporaneous news (build step 6). The 20:00 rung's one-minute window limits contamination on the clean subset; later rungs are unprotected.
- **Spread at event.** Unknowable; costs will use the live snapshot and say so.
- **Monday-type ex-dates and weekend sessions.** Too few events.
- **Sample period.** Six weeks, one payment batch, promotional 0.05% fee period, a three-month-old product. The public announcement API returns only recent items; later batches, if any, are not in the ledger.
- **In-place split adjustment** (a split without a re-listing) remains ASSUMED; no such case exists.
"""
(ROOT / "docs" / "m0.md").write_text(doc)
print("rendered", len(doc), "chars")
